version: '3.8'

services:
  db:
    image: postgres:16.6-alpine
    environment:
      POSTGRES_DB: telegram_collector
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  collector:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
    env_file:
      - ../.env
    volumes:
      - ../sessions:/app/sessions
    restart: unless-stopped

volumes:
  postgres_data: 